import { describe, expect, it } from "vitest";

import {
  buildCandidateConnectionUrls,
  databaseNameFromUrl,
  maintenanceDatabaseUrl,
  mergeApiEnv,
  redactDatabaseUrl,
} from "../../../scripts/dev-lib.mjs";

describe("dev startup helpers", () => {
  it("builds database candidates in the documented probe order", () => {
    expect(buildCandidateConnectionUrls({ DATABASE_URL: "postgres://user:secret@example.test:5432/custom" })).toEqual([
      {
        label: "DATABASE_URL",
        url: "postgres://user:secret@example.test:5432/custom",
        reason: "DATABASE_URL is set in the current shell",
      },
      {
        label: "localhost:5433",
        url: "postgres://postgres@localhost:5433/cartwise",
        reason: "trust-auth local Postgres on port 5433",
      },
      {
        label: "localhost:5432",
        url: "postgres://postgres@localhost:5432/cartwise",
        reason: "trust-auth local Postgres on port 5432",
      },
    ]);
  });

  it("omits the DATABASE_URL candidate when the shell does not provide one", () => {
    expect(buildCandidateConnectionUrls({}).map((candidate) => candidate.label)).toEqual(["localhost:5433", "localhost:5432"]);
  });

  it("rewrites a connection URL to the maintenance database", () => {
    expect(maintenanceDatabaseUrl("postgres://postgres@localhost:5433/cartwise")).toBe(
      "postgres://postgres@localhost:5433/postgres",
    );
  });

  it("extracts a database name with a cartwise fallback", () => {
    expect(databaseNameFromUrl("postgres://postgres@localhost:5433/custom")).toBe("custom");
    expect(databaseNameFromUrl("postgres://postgres@localhost:5433")).toBe("cartwise");
  });

  it("redacts passwords in URLs used for console output", () => {
    expect(redactDatabaseUrl("postgres://user:secret@localhost:5432/cartwise")).toBe(
      "postgres://user:****@localhost:5432/cartwise",
    );
  });

  it("refreshes DATABASE_URL while preserving Kroger and Target settings", () => {
    const existing = [
      "DATABASE_URL=postgres://old",
      "KROGER_CLIENT_ID=abc",
      "PORT=3000",
      "TARGET_DISABLED=1",
      "SOMETHING_ELSE=ignored",
    ].join("\n");

    expect(mergeApiEnv(existing, "postgres://postgres@localhost:5433/cartwise")).toBe(
      [
        "# Generated by npm run dev. Kroger/Target settings below are preserved.",
        "DATABASE_URL=postgres://postgres@localhost:5433/cartwise",
        "",
        "KROGER_CLIENT_ID=abc",
        "TARGET_DISABLED=1",
        "",
      ].join("\n"),
    );
  });
});
