const DEFAULT_DB_NAME = "cartwise";

export function buildCandidateConnectionUrls(env = process.env) {
  const candidates = [];

  if (env.DATABASE_URL) {
    candidates.push({
      label: "DATABASE_URL",
      url: env.DATABASE_URL,
      reason: "DATABASE_URL is set in the current shell",
    });
  }

  for (const port of [5433, 5432]) {
    candidates.push({
      label: `localhost:${port}`,
      url: `postgres://postgres@localhost:${port}/${DEFAULT_DB_NAME}`,
      reason: `trust-auth local Postgres on port ${port}`,
    });
  }

  return candidates;
}

export function databaseNameFromUrl(connectionUrl, fallback = DEFAULT_DB_NAME) {
  try {
    const url = new URL(connectionUrl);
    const pathname = decodeURIComponent(url.pathname.replace(/^\/+/, ""));
    return pathname || fallback;
  } catch {
    return fallback;
  }
}

export function withDatabaseName(connectionUrl, databaseName) {
  const url = new URL(connectionUrl);
  url.pathname = `/${encodeURIComponent(databaseName)}`;
  return url.toString();
}

export function maintenanceDatabaseUrl(connectionUrl) {
  return withDatabaseName(connectionUrl, "postgres");
}

export function redactDatabaseUrl(connectionUrl) {
  try {
    const url = new URL(connectionUrl);
    if (url.password) {
      url.password = "****";
    }
    return url.toString();
  } catch {
    return "<invalid DATABASE_URL>";
  }
}

export function mergeApiEnv(existingEnvText, databaseUrl) {
  const generatedHeader = "# Generated by npm run dev. Existing settings are preserved; managed values are refreshed.";
  const legacyGeneratedHeader = "# Generated by npm run dev. Kroger/Target/Walmart/ALDI settings below are preserved.";
  const managedValues = new Map([["DATABASE_URL", databaseUrl]]);
  const lines = existingEnvText.replace(/\r\n/g, "\n").split("\n");
  if (lines.at(-1) === "") {
    lines.pop();
  }

  const mergedLines = [];
  const seenManagedKeys = new Set();
  let hasGeneratedHeader = false;

  for (const line of lines) {
    if (line === generatedHeader || line === legacyGeneratedHeader) {
      if (!hasGeneratedHeader) {
        mergedLines.push(generatedHeader);
        hasGeneratedHeader = true;
      }
      continue;
    }

    const assignment = parseEnvAssignment(line);
    const managedValue = assignment ? managedValues.get(assignment.key) : undefined;
    if (managedValue !== undefined) {
      if (!seenManagedKeys.has(assignment.key)) {
        mergedLines.push(`${assignment.prefix}${assignment.key}${assignment.separator}${managedValue}`);
        seenManagedKeys.add(assignment.key);
      }
      continue;
    }

    mergedLines.push(line);
  }

  if (!hasGeneratedHeader) {
    mergedLines.unshift(generatedHeader);
  }

  const headerIndex = mergedLines.indexOf(generatedHeader);
  const missingManagedLines = [];
  for (const [key, value] of managedValues) {
    if (!seenManagedKeys.has(key)) {
      missingManagedLines.push(`${key}=${value}`);
    }
  }
  mergedLines.splice(headerIndex + 1, 0, ...missingManagedLines);

  return `${mergedLines.join("\n")}\n`;
}

function parseEnvAssignment(line) {
  const match = line.match(/^(\s*(?:export\s+)?)([A-Za-z_][A-Za-z0-9_]*)(\s*=\s*)(.*)$/);
  if (!match) {
    return null;
  }

  return {
    prefix: match[1],
    key: match[2],
    separator: match[3],
  };
}
