const DEFAULT_DB_NAME = "cartwise";

export function buildCandidateConnectionUrls(env = process.env) {
  const candidates = [];

  if (env.DATABASE_URL) {
    candidates.push({
      label: "DATABASE_URL",
      url: env.DATABASE_URL,
      reason: "DATABASE_URL is set in the current shell",
    });
  }

  for (const port of [5433, 5432]) {
    candidates.push({
      label: `localhost:${port}`,
      url: `postgres://postgres@localhost:${port}/${DEFAULT_DB_NAME}`,
      reason: `trust-auth local Postgres on port ${port}`,
    });
  }

  return candidates;
}

export function databaseNameFromUrl(connectionUrl, fallback = DEFAULT_DB_NAME) {
  try {
    const url = new URL(connectionUrl);
    const pathname = decodeURIComponent(url.pathname.replace(/^\/+/, ""));
    return pathname || fallback;
  } catch {
    return fallback;
  }
}

export function withDatabaseName(connectionUrl, databaseName) {
  const url = new URL(connectionUrl);
  url.pathname = `/${encodeURIComponent(databaseName)}`;
  return url.toString();
}

export function maintenanceDatabaseUrl(connectionUrl) {
  return withDatabaseName(connectionUrl, "postgres");
}

export function redactDatabaseUrl(connectionUrl) {
  try {
    const url = new URL(connectionUrl);
    if (url.password) {
      url.password = "****";
    }
    return url.toString();
  } catch {
    return "<invalid DATABASE_URL>";
  }
}

export function mergeApiEnv(existingEnvText, databaseUrl) {
  const preservedLines = existingEnvText
    .split(/\r?\n/)
    .filter((line) => /^\s*(?:export\s+)?(?:KROGER_|TARGET_|WALMART_|ALDI_)[A-Z0-9_]*\s*=/.test(line));

  const lines = [
    "# Generated by npm run dev. Kroger/Target/Walmart/ALDI settings below are preserved.",
    `DATABASE_URL=${databaseUrl}`,
  ];

  if (preservedLines.length > 0) {
    lines.push("", ...preservedLines);
  }

  return `${lines.join("\n")}\n`;
}
